# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://jiayue0107.github.io/Log/
date_format: "ordinal"
title: Log
subtitle: "Object not found exception"
description: "贾悦的个人博客"
keywords: Log, Yue Jia, jiayue
favicon: /Log/favicon.ico
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Yue Jia
organization: 
organization_url: 
location: Beijing, China
email: cloundg@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /Log/
    label: 首页

  -
    href: /Log/categories/
    label: 分类

  -
    href: /Log/wiki/
    label: 维基

  -
    href: /Log/links/
    label: 链接

  -
    href: /Log/about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /Log/feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: Log/jiayue0107.github.io
# ---------------- #
#      Socials     #
# ---------------- #
github_username: jiayue0107
douban_username: Zwei
facebook_username: 贾悦
weibo_username: JiaYue0107
zhihu_username: 贾悦
twitter_username: JiaYue0107

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: JY
disqus_username: Yue jia
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, Object C]
skill_mobile_app_keywords: [Android,iOS]
skill_windows_keywords: []
