# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://3dincremnt@gmail.com
date_format: "ordinal"
title: 3D increment
subtitle: "3D 打印改变生活"
description: "3D increment blog"
keywords: 3D printing, increment, recuite
#timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: increment
organization: 3D increment
organization_url: https://3dincrement.github.io/
github_username: mzlogin
location: Qingdao, China
email: 3dincremnt@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: 3dincrement/3dincrement.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 3dincrement
    repo: 3dincrement.github.io
    oauth:
        client_id: 6aac903760c8b3b313e8
        client_secret: 0696db07ba2897d037fcac78c3575d317ce990c6
# https://github.com/gitalk/gitalk#install
gitalk:
    owner:  3dincrement
    repo: 3dincrement.github.io
    clientID: 6aac903760c8b3b313e8
    clientSecret: 0696db07ba2897d037fcac78c3575d317ce990c6
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
