# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://blog.sqdyy.cn
date_format: "ordinal"
title: 神奇的鸭鸭の码农库
subtitle: "全栈程序员/初级产品经理/初级设计师/极限运动玩家"
description: "韦耿林的个人博客"
keywords: 神奇的鸭鸭の码农库, 韦耿林
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Geng Lin Wei
organization: 
organization_url: 
github_username: SQDYY
location: ShenZheng, China
email: 702038338@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页
  -
    href: /categories/
    label: 分类
  -
    href: /wiki/
    label: 维基
  -
    href: /links/
    label: 链接
  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: SQDYY/SQDYY.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: SQDYY
    repo: blog-comments
    oauth:
        client_id: 17f1cdc16ff445ac2d95
        client_secret: 28b52f230c80a89468325df1aa6386497e4805ee
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: SQDYY
    repo: blog-comments
    client_id: 17f1cdc16ff445ac2d95
    client_secret: 28b52f230c80a89468325df1aa6386497e4805ee
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
